trigger:
- master

stages:
- stage: "BuildStage"
  displayName: Build
  jobs:
  - job: "BuildJob"
    pool:
      vmImage: ubuntu-latest

    variables:
      buildConfig: 'Release'

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfig)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfig)  --output $(Build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: "DeployToDev"
  dependsOn: "BuildStage"
  jobs:
  - job: 
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go(174740a9-79b5-4c67-87dc-5c83aa1d1c90)'
        appType: 'webAppLinux'
        WebAppName: 'PraBhoWebAppCiCdDev'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
        # packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        RuntimeStack: 'DOTNETCORE|6.0'

- stage: "DeployToQa"
  # dependsOn: "DeployToDev"
  condition: eq(variables['Build.Reason'], 'Manual')
  jobs:
  - job: 
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go(174740a9-79b5-4c67-87dc-5c83aa1d1c90)'
        appType: 'webAppLinux'
        WebAppName: 'PraBhoWebAppCiCdQA'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
        RuntimeStack: 'DOTNETCORE|6.0'
    
